### ISSUE TITLE
[Feature Request] Add column explanations

### ISSUE THREAD

**Issue by gene1wood** [HarvsG/WireGuardMeshes#12]
**Is your feature request related to a problem? Please describe.**

Would it be possible to add explanations for what each column means, some of them (like `Subnet Access` aren't clear to me)?

**Describe the solution you'd like**

Either just a section at the bottom of the README that lists out the column headers and what they mean or mouseover text for each column header with the description

**Comment by HarvsG** [comment]
I think that this is fair. I also find that the definitions flex in my head when I am adding new rows, so it would be helpful to have definitions set in stone.

**Comment by HarvsG** [comment]
Fixed in #23
