### ISSUE TITLE
[Correction]

### ISSUE THREAD

**Issue by justin13888** [HarvsG/WireGuardMeshes#13]
**Describe the error and suggest correction**
A clear and concise description of what the error is and what the correct emoji/text should be in each box. Reference the boxes to be corrected using `row`/`column` e.g `wireguard vanilla`/`iOS`, `android`

Android clients will be supported for Headscale soon by the Tailscale client on Android (currently in testing).

So the box for Headscale/Android should be ✅ (not ❌) and maybe with an asterisk.

**Evidence and Justification**
The PR with this functionality could be found here: https://github.com/tailscale/tailscale-android/pull/45#issuecomment-1202017001

**Comment by HarvsG** [comment]
Solved in https://github.com/HarvsG/WireGuardMeshes/pull/19
