### ISSUE TITLE
[Feature Request] Firezone

### ISSUE THREAD

**Issue by autonompost** [HarvsG/WireGuardMeshes#18]
please add 

https://github.com/firezone/firezone

WireGuard®-based VPN server and firewall

**Comment by HarvsG** [comment]
Firezone is explicitly not a tool for creating mesh networks

![image](https://user-images.githubusercontent.com/11440490/195587147-de756c2c-7559-4e6d-af59-5720a566ac29.png)

May be a candidate for inclusion in https://github.com/cedrickchee/awesome-wireguard if it is not already
