### ISSUE TITLE
[Feature Request] Explain what does 'spoke' mean

### ISSUE THREAD

**Issue by jruiz94** [HarvsG/WireGuardMeshes#26]
Hello, just a small question that might help others too, what does 'spoke' mean in the text: "_Client can join as a 'spoke' off a node/gateway on the mesh_"? I don't quite understand the concept of 'spoke'.

Others might find helpful to have a brief explanation as a side note to this concept too (or maybe I'm the only one that doesn't know this concept haha)

**Comment by HarvsG** [comment]
Spoke is from the hub-and-spoke model of networking.
If you understand what a mesh is then you are v. unlikely to understand what a hub and spoke model is
https://www.google.com/search?q=networking+hub+and+spoke+model&oq=networking+hub+and+spoke+model
