### ISSUE TITLE
[Correction] Tailscale free tier update

### ISSUE THREAD

**Issue by sergioponguta** [HarvsG/WireGuardMeshes#28]
**Describe the error and suggest correction**
Tailscale free tier is now up to 100 devices and 3 users, should be updated on the comparation table.

**Evidence and Justification**

![image](https://user-images.githubusercontent.com/24575078/235324230-9225c472-1418-46d9-ba04-2fd1cf4bc17f.png)
[Link to tailscale pricing](https://tailscale.com/pricing/)

**Comment by HarvsG** [comment]
Thank you for pointing this out. I don't have access to my PC for a a week or so. Otherwise I can accept a PR

**Comment by sergioponguta** [comment]
> Thank you for pointing this out. I don't have access to my PC for a a week or so. Otherwise I can accept a PR

I will create a PR in a bit

**Comment by sergioponguta** [comment]
Now its done, waiting for approve #29

**Comment by HarvsG** [comment]
Fixed in #29
